### ISSUE TITLE
TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

### ISSUE THREAD

**Issue by ganesh-phadtare** [sketch7/angular-skeleton-app#6]
Browser : chrome v65.0.3325.181

I am facing an issue as TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script. This issue is occurring when I execute command as 
`ng build -- prod`

Detail error is like 
main.27194690c35d3972faa9.bundle.js:1 ERROR Error: Uncaught (in promise): TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

and when I inspect the chrome browser - in the network tab "ngsw-worker.js" is showing the status as failed.

**Comment by stephenlautier** [comment]
I just tried it again and it seems that its working fine.

```
npm i
npm run start:prod
```
Dont use `ng build -- prod` (you have a typo there)

Did you update anything or recreated lock file perhaps?

**Comment by stephenlautier** [comment]
Recreated package lock and it still working fine, use the command i suggested and see if it works

**Comment by BLecha** [comment]
@stephenlautier  but if I one needs to use ng build --prod?

**Comment by stephenlautier** [comment]
@BLecha you can, it just need to be written properly. 

As commented above, either use 

```bash
# shorthand
npm run start:prod

# or else 
npm run build -- --prod

# or as you wrote it directly (but becareful because that uses the global)
ng build --prod
```

**Comment by BLecha** [comment]
@stephenlautier  have you deployed angular pwa app on local IIS?
